alias ins='sudo apt install'
alias emacs='emacs -nw'
alias emasc='emacs -nw'
alias st='~/Documents/programs/st/st'
alias dmenu='~/Documents/.tmuxrc/dmenu/dmenu'
alias surf='~/Documents/.tmuxrc/surf/surf'
alias x='exit'
alias d='tmux detach-client'
alias screenshot='source ~/Documents/.tmuxrc/scripts/screenshot.sh'

PS1='\[\033[34m\]\w\n\[\033[37m\]-> '
