addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libdbus-1-dev
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxss-dev
      - libglib2.0-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libnotify-dev
      - libgtk-3-dev
      - valgrind
dist: xenial
sudo: false
language: c

git:
  depth: false

before_install:
  - pip install --user cpp-coveralls

script:
  - CFLAGS="-Werror" make all dunstify test-valgrind doc-doxygen
  - ./test/test-install.sh
  - CFLAGS="-Werror" make clean
  - CFLAGS="-Werror" make test-coverage

matrix:
  include:
    - compiler: gcc
      after_success:
        - coveralls
    - compiler: clang
