version: 2.1
jobs:
  misc-doxygen:
    docker:
      - image: dunst/ci:misc-doxygen
    environment:
      SYSTEMD: 0
      SERVICEDIR_DBUS: /tmp/none
      SERVICEDIR_SYSTEMD: /tmp/none
      PKG_CONFIG: echo
    steps:
      - checkout
      - run: make -j doc-doxygen

  compileandtest:
    environment:
      CFLAGS: -Werror
    parameters:
      distro:
        type: string
    docker:
      - image: dunst/ci:<<parameters.distro>>
    steps:
      - checkout
      - run: make CC=clang -j all dunstify test/test
      - run: make CC=clang -j test-valgrind
      - run: ./test/test-install.sh
      - run: make             clean
      - run: make CC=gcc   -j all dunstify test/test
      - run: make CC=gcc   -j test-valgrind
      - run: make             clean
      - run: make          -j test-coverage

workflows:
  version: 2
  build-in-docker:
    jobs:
      - misc-doxygen
      - compileandtest:
          name: Alpine
          distro: alpine
      - compileandtest:
          name: Debian Stretch
          distro: debian-stretch
          requires:
            - misc-doxygen
            - Alpine
      - compileandtest:
          name: Arch Linux
          distro: archlinux
          requires:
            - misc-doxygen
            - Alpine
      - compileandtest:
          name: Fedora 30
          distro: fedora30
          requires:
            - misc-doxygen
            - Alpine
      - compileandtest:
          name: Ubuntu 16.04
          distro: ubuntu-xenial
          requires:
            - misc-doxygen
            - Alpine
      - compileandtest:
          name: Ubuntu 18.04
          distro: ubuntu-bionic
          requires:
            - misc-doxygen
            - Alpine
