#!/bin/bash

choices="0%\n20%\n40%\n60%\n80%\n100%\nexit"
choice=$( echo -e $choices | rofi -dmenu -p "Keyboard backlight: ")

case $choice in
    "exit")
        exit
        ;;
    "0%")
        echo 0 > /sys/class/leds/smc\:\:kbd_backlight/brightness
        ;;
    "20%")
        echo 50 > /sys/class/leds/smc\:\:kbd_backlight/brightness
        ;;
    "40%")
        echo 100 > /sys/class/leds/smc\:\:kbd_backlight/brightness
        ;;
    "60%")
        echo 150 > /sys/class/leds/smc\:\:kbd_backlight/brightness
        ;;
    "80%")
        echo 200 > /sys/class/leds/smc\:\:kbd_backlight/brightness
        ;;
    "100%")
        echo 255 > /sys/class/leds/smc\:\:kbd_backlight/brightness
        ;;
    *)
esac
simplenotify -t "Keyboard Backlight $choice" --timeout 2 --reset --id "keyboard backlight"

