#!/bin/bash
# music player

if tmux ls | grep -q "music"
then
    st -e tmux new-session -A -s music
else
    tmux new-session -d -s music 'cmus';
    tmux split-window -t music -p 20 'cava' \;
    st -e tmux a -t music
fi
