#!/bin/bash

choices="Lock\nLogout\nReboot\nReset DWM\nShutdown\nSuspend"
choice=$( echo -e $choices | rofi -dmenu -p "Power Options")

case $choice in
	"Lock")
		dm-tool lock
		# slock
		;;
	"Logout")
		xsetroot -name "fsignal:1"
		;;
    "Shutdown")
        shutdown 0
        ;;
	"Suspend")
        systemctl suspend
        ;;
	"Reboot")
		shutdown -r 0
		;;
	"Reset DWM")
		xsetroot -name "fsignal:2"
		;;
esac
