#!/bin/bash

choices="Lockout\nReboot\nShutdown\nSuspend\nLock"
choice=$( echo -e $choices | rofi -dmenu -p "Power Options")

case $choice in
	"Lockout")
		dm-tool lock
		;;
	"Reboot")
		shutdown -r 0
		;;
    "Shutdown")
        shutdown 0
        ;;
    "Suspend")
        systemctl suspend
        ;;
    "Lock")
        slock
        ;;
    *)
esac
