#!/bin/bash

choices="Shutdown\nSuspend\nLock"
choice=$( echo -e $choices | rofi -dmenu -p "Volume")

case $choice in
    "Shutdown")
        shutdown 0
        ;;
    "Suspend")
        systemctl suspend
        ;;
    "Lock")
        slock
        ;;
    *)
esac
