#!/bin/bash

choices="screenshot\nfullscreen screenshot\nscreenrecording\nobs\nexit"
choice=$( echo -e $choices | rofi -dmenu -p "Screenshot Applications")

case $choice in
    "screenshot")
        rm -f /tmp/tmp.png
		    scrot -s --line mode=edge /tmp/tmp.png && xclip -selection clipboard -t image/png -i /tmp/tmp.png
        ;;
    "fullscreen screenshot")
        sleep .2
        scrot /tmp/tmp.png && xclip -selection clipboard -t image/png -i /tmp/tmp.png && rm /tmp/tmp.png
        ;;
    "screenrecording")
        kazam
        ;;
	"obs")
		obs
		;;
    *)
esac

